//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelScoreStat
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public System.DateTime DateTime { get; set; }
        public int LevelNumber { get; set; }
        public int Score { get; set; }
        public int Version { get; set; }
        public int Stars { get; set; }
        public int PatientsHealed { get; set; }
        public int PatientsKilled { get; set; }
    }
}
